version: '3.8'



services:
  server:
    build: ewm-stats/server
    container_name: ewm_stats_server
    depends_on:
     - stats-db
    ports:
      - "9090:9090"
    environment:
      #- TZ=Europe/Moscow
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  stats-db:
    image: postgres:13.7-alpine
    container_name: ewm-stats-db

    ports:
    - "6541:5432"
    environment:
    #- TZ=Europe/Moscow
    - POSTGRES_DB=stats
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres

